import{a as v,i as u,S as b}from"./assets/vendor-D73Uttp0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();function p(o){return o.map(({webformatURL:t,largeImageURL:a,tags:s,likes:e=0,views:r=0,comments:i="",downloads:y=0})=>`
            <div class="galleries">
                <div class="loader" style="display: block;"></div> 
                <a href="${a}">
                    <img src="${t}" alt="${s}" />
                </a>
                <div class="content">
                    <div><p>Likes</p><span>${e}</span></div>
                    <div><p>Views</p><span>${r}</span></div>
                    <div><p>Comments</p><span>${i}</span></div>
                    <div><p>Downloads</p><span>${y}</span></div>
                </div>
            </div>`).join("")}function m(o){o.querySelectorAll(".galleries img").forEach(a=>{const s=a.parentElement.previousElementSibling;a.onload=()=>{s.style.display="none"},a.onerror=()=>{s.style.display="none"}})}const L="46815109-801c3b1dec2424a02adace61a",S="https://pixabay.com/api/";let g=15;async function f(o,t=1){return await v.get(S,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:g}})}const h=document.querySelector(".form"),c=document.querySelector(".gallery"),n=document.querySelector(".btn-add-more");let l=null,d=1;h.addEventListener("submit",w);async function w(o){o.preventDefault();const{textRow:t}=o.target.elements;if(localStorage.setItem("searchItem",JSON.stringify(t.value)),t.value.trim()===""){u.warning({title:"Caution",message:"The search field cannot be empty.",color:"red",position:"topRight",maxWidth:"300"});return}try{const{data:a}=await f(t.value);a.hits.length?(c.innerHTML=p(a.hits),n.classList.add("js-vissible"),m(c),l?l.refresh():l=new b(".gallery .galleries a",{captionsData:"alt",captionDelay:250})):u.warning({title:"Caution",message:'"Sorry, there are no images matching your search query. Please try again!"',color:"yellow",position:"topRight",maxWidth:"300"})}catch(a){console.log(a.message)}h.reset()}n.addEventListener("click",()=>{n.disabled=!0;const o=JSON.parse(localStorage.getItem("searchItem"));d+=1,f(o,d).then(t=>{const a=t.data.totalHits,s=Math.ceil(a/g);d>=s&&(n.classList.replace("js-vissible","js-hidden"),u.warning({title:"Caution",message:"We're sorry, but you've reached the end of search results.",color:"yellow",position:"topRight",maxWidth:"300"})),c.insertAdjacentHTML("beforeend",p(t.data.hits));const r=document.querySelector(".galleries").getBoundingClientRect().height;return window.scrollBy({left:0,top:r*2,behavior:"smooth"}),l.refresh(),m(c)}).catch(t=>console.log(t.message)).finally(()=>n.disabled=!1)});
//# sourceMappingURL=index.js.map
