import{a as v,i as p,S as b}from"./assets/vendor-D73Uttp0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();function u(o){return o.map(({webformatURL:t,largeImageURL:r,tags:s,likes:e=0,views:a=0,comments:n="",downloads:y=0})=>`
            <div class="galleries">
                <div class="loader" style="display: block;"></div> 
                <a href="${r}">
                    <img src="${t}" alt="${s}" />
                </a>
                <div class="content">
                    <div><p>Likes</p><span>${e}</span></div>
                    <div><p>Views</p><span>${a}</span></div>
                    <div><p>Comments</p><span>${n}</span></div>
                    <div><p>Downloads</p><span>${y}</span></div>
                </div>
            </div>`).join("")}function m(o){o.querySelectorAll(".galleries img").forEach(r=>{const s=r.parentElement.previousElementSibling;r.onload=()=>{s.style.display="none"},r.onerror=()=>{s.style.display="none"}})}const L="46815109-801c3b1dec2424a02adace61a",w="https://pixabay.com/api/";let g=15;async function h(o,t=1){return await v.get(w,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:g}})}const f=document.querySelector(".form"),l=document.querySelector(".gallery"),i=document.querySelector(".btn-add-more");let c=null,d=1;f.addEventListener("submit",S);async function S(o){o.preventDefault();const{textRow:t}=o.target.elements;if(d=1,localStorage.setItem("searchItem",JSON.stringify(t.value)),t.value.trim()===""){p.warning({title:"Caution",message:"The search field cannot be empty.",color:"red",position:"topRight",maxWidth:"300"});return}try{const{data:r}=await h(t.value);r.hits.length?(l.innerHTML=u(r.hits),i.classList.add("js-vissible"),m(l),c?c.refresh():c=new b(".gallery .galleries a",{captionsData:"alt",captionDelay:250})):(l.innerHTML="",i.classList.add("js-hidden"),p.warning({title:"Caution",message:'"Sorry, there are no images matching your search query. Please try again!"',color:"yellow",position:"topRight",maxWidth:"300"}))}catch(r){console.log(r.message)}f.reset()}i.addEventListener("click",async()=>{i.disabled=!0;const o=JSON.parse(localStorage.getItem("searchItem"));d+=1;try{const{data:t}=await h(o,d),r=t.totalHits,s=Math.ceil(r/g);d>=s&&(i.classList.replace("js-vissible","js-hidden"),p.warning({title:"Caution",message:"We're sorry, but you've reached the end of search results.",color:"yellow",position:"topRight",maxWidth:"300"})),l.insertAdjacentHTML("beforeend",u(t.hits));const a=document.querySelector(".galleries").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"}),m(l),c.refresh()}catch(t){console.error("Error loading more images:",t.message),p.error({title:"Error",message:"An error occurred while loading more images. Please try again.",color:"red",position:"topRight",maxWidth:"300"})}finally{i.disabled=!1}});
//# sourceMappingURL=index.js.map
